language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - $HOME/.cargo/git
  - $HOME/.cargo/registry
  - $TRAVIS_BUILD_DIR/target
services:
  - docker
jobs:
  include:
    - stage: Build
      script:
        - docker pull cita/cita-build:ubuntu-18.04-20180523
        - bash '.ci-scripts/format'
        - bash '.ci-scripts/build'
